# Generated by Django 3.0 on 2019-12-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abscissa', models.DecimalField(decimal_places=10, help_text='x', max_digits=10)),
                ('ordinate', models.DecimalField(decimal_places=10, help_text='y', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'PLAYED'), (2, 'DONE')])),
                ('figure', models.IntegerField(choices=[(0, 'SQUARE'), (1, 'TRIANGLE_TYPE_1'), (2, 'TRIANGLE_TYPE_2'), (3, 'TRIANGLE_TYPE_3')])),
            ],
        ),
        migrations.CreateModel(
            name='UserJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Dot')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', through='room.UserJoin', to=settings.AUTH_USER_MODEL),
        ),
    ]
